### ISSUE TITLE
Demo kinect-3d-slam crashes

### ISSUE THREAD

**Issue by jlblancoc** [jlblancoc/mrpt#125]
Exception is: 

```
mrpt::tfest::se3_l2_robust, line 64:
Minimum number of points to be considered a good set is < Minimum number of points to fit the model
```

**Comment by SuperContraptionGuy** [comment]
I have the same issue.

**Comment by ensonic** [comment]
Updated the git repo, but it does not build: https://gist.github.com/ensonic/1bbd00797f3ef7794a80

**Comment by jlblancoc** [comment]
Yes, just noticed it. I'll fix it soon, but in the meanwhile you can
checkout the previous commit version.

JL


On Mon, Jul 6, 2015 at 10:14 PM, Stefan Sauer <notifications@github.com>
wrote:

> Updated the git repo, but it does not build:
> https://gist.github.com/ensonic/1bbd00797f3ef7794a80
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlblancoc/mrpt/issues/125#issuecomment-118982176>.
>



-- 
___________________________________________________________

Dr. Jose-Luis Blanco-Claraco
CITE-IV 1.05
Universidad de Almería, Departamento de Ingeniería
04120 Almería (Spain)
http://www.ual.es/~jlblanco/
___________________________________________________________

**Comment by ensonic** [comment]
Thanks, build fine now!
