### ISSUE TITLE
Eigen Alignment Errors with CObservation6DFeatures

### ISSUE THREAD

**Issue by cpitman** [jlblancoc/mrpt#141]
I am getting alignment assertions randomly while executing the following line:

    mrpt::obs::CObservation6DFeaturesPtr frameObservations = mrpt::obs::CObservation6DFeatures::Create();
    mrpt::obs::CObservation6DFeatures::TMeasurement measurement;
    frameObservations->sensedFeatures.push_back(measurement);

I am new to both MRPT and Eigen, but could it be an issue that the deque that the measurements are being pushed onto is using a `std::allocator` instead of an Eigen specific one?

https://github.com/jlblancoc/mrpt/blob/master/libs/obs/include/mrpt/obs/CObservation6DFeatures.h#L47

**Comment by jlblancoc** [comment]
You're absolutely right, thanks! 

I can't fix it at the moment, it would be great if you could fork, modify and issue a pull request after checking the following fix: 

Replace `std::deque<TMeasurement>` with `mrpt::aligned_containers<TMeasurement>::deque_t` in the .h and perhaps when needed in the .cpp file.

Cheers.
