### ISSUE TITLE
CPointsMap & kdTree: search radius - doxygene

### ISSUE THREAD

**Issue by KDemeul** [jlblancoc/mrpt#153]
There seems to be a small issue with the doxygene about the function relative to kdTree radius search (such as ```kdTreeRadiusSearch3D(...)```). I might be wrong, but I think that the parameters ```const floatmaxRadius``` should be the squared distance of the radius distance. 
For instance: 
I want to search for all points in the range [0,20] of a given point p=(x,y,z), then i should use:

``` myMap.kdTreeRadiusSearch3D(x,y,z,20*20,out_indices_dist) ```

The kd-tree attached to CPointsMap (and its children) is using the L2 norm (```nanoflann::L2_Simple_Adaptor```). Taking a look at nanoflann, its the square of the L2 norm that is used.

Cheers,

Kilian.

**Comment by jlblancoc** [comment]
Correct! :+1:
