### ISSUE TITLE
wxWidgets was not found automatically. Please, set wxWidgets_ROOT_DIR to the lib directory to enable it in MRPT. How should I fix it?

### ISSUE THREAD

**Issue by 5aou** [jlblancoc/mrpt#160]
Hi all, I encounter this error when I do : ccmake .
wxWidgets was not found automatically. Please, set wxWidgets_ROOT_DIR to the lib directory to enable it in MRPT. Can you tell me please how should I fix it? thank you a lot.

Using : linux mint.

**Comment by jlblancoc** [comment]
I guess you should install the -dev or -devel package equivalent for
wxWidgets in Linux mint, and then CMake should find it automatically...

JL


On Thu, Jul 16, 2015 at 11:34 AM, 5aou <notifications@github.com> wrote:

> Hi all, I encounter this error when I do : ccmake .
> wxWidgets was not found automatically. Please, set wxWidgets_ROOT_DIR to
> the lib directory to enable it in MRPT. Can you tell me please how should I
> fix it? thank you a lot.
>
> Using : linux mint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlblancoc/mrpt/issues/160>.
>



-- 
___________________________________________________________

Dr. Jose-Luis Blanco-Claraco
CITE-IV 1.05
Universidad de Almería, Departamento de Ingeniería
04120 Almería (Spain)
http://www.ual.es/~jlblanco/
___________________________________________________________

**Comment by 5aou** [comment]
Ok thank you, it works now.

**Comment by 5aou** [comment]
re, I want to implement a kf-slam to have results like those : https://www.youtube.com/watch?v=eOkzd_i_-ps  (camera poses), but the application page : http://www.mrpt.org/Application:kf-slam/ gives me an error. Can you give me please a tutorial or another page where I can find the application.... thank you a lot.
