### ISSUE TITLE
Assertion failure error by missing ALIGN* macro. (HMT-SLAM) 

### ISSUE THREAD

**Issue by TK135** [jlblancoc/mrpt#94]
HMTSLAM library in 32bit.ver have Assertion failure error.

I think this error occurs when executing "CGridMapAligner" class.
 Error message is like this

*************************************************************************************************************************
[CGridMapAligner] Overall estimation(26 corrs, total: 49): (-2.385,1.491,43.590deg)      <====  error often occurrs after this message

Assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamil
y.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file e:\backups\mrpt.org_ciencia-
explicada\mrpt_releases\mrpt-release-1.2.1\mrpt-1.2.1\otherlibs\eigen3\eigen\src/Core/DenseStorage.h, line 78
*************************************************************************************************************************

**Comment by jlblancoc** [comment]
@TK135 Thanks for reporting! It's finally fixed with the patch in 9c9b7c1
